### auth signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "sobralcassique@gmail.com",
    "password": "1234567919",
    "name": "Cassiano5",
    "role": "advertiser",
    "advertiserData": {
        "isAdvertiser": true,
        "companyName": "Minha Empresa",
        "contactEmail": "sobralcassique@gmail.com",
        "phone": "11999999999",
        "businessType": "company",
        "totalAnnouncements": 0,
        "activeAnnouncements": 0,
        "totalSpent": 0,
        "status": "active",
        "verificationStatus": "pending",
        "properties": []
    }
  
}
### verify email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
    "email": "sobralcassique@gmail.com",
    "verificationToken":"89827"
}

### resend verification token / signup or password
POST http://localhost:3000/auth/resend-verification-token
Content-Type: application/json

{
    "email":"sobralcassique@gmail.com",
    "type":"verification"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"sobralcassique@gmail.com",
    "password":"1234567919",
    "role":"advertiser"
}
### logout 
POST http://localhost:3000/auth/logout

### get user 
POST http://localhost:3000/auth/user
Content-Type: application/json

{
    "email":"sobralcassique@gmail.com"
}
### forgot password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
    "email":"sobralcassique@gmail.com"
}
### reset password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
    "token":"55864",
    "email":"sobralcassique@gmail.com",
    "newPassword":"TesteReal2"
}

### signup with google
GET http://localhost:3000/auth/google

### complete signup with google
POST http://localhost:3000/auth/google/complete-signup
Content-Type: application/json

{
  "role": "advertiser",
  "user": {
    "advertiserData": {
      "isAdvertiser": true,
      "companyName": "Minha Empresa",
      "contactEmail": "sobralcassique@gmail.com",
      "phone": "11999999999",
      "businessType": "company",
      "totalAnnouncements": 0,
      "activeAnnouncements": 0,
      "totalSpent": 0,
      "status": "active",
      "verificationStatus": "pending"
    }
  },
  "email": "sobralcassique@gmail.com"
}
### logout with google
POST http://localhost:3000/auth/logoutGoogle
Content-Type: application/json

{
    "email": "emprego1231231@gmail.com"
}
### get profile advertiser
POST http://localhost:3000/advertiser/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODEyYzA0Mjc4MTZkM2UwNzg1YWI2ZSIsImVtYWlsIjoic29icmFsY2Fzc2lxdWVAZ21haWwuY29tIiwiaWF0IjoxNzUzMzA4ODQ2LCJleHAiOjE3NTMzOTUyNDZ9.3Wvjb0Al0SgCxUty0_rWQXb631fu4nYKi5lf2M5-_S0
Content-Type: application/json

{
    "userId":"68812c0427816d3e0785ab6e"
}

### update profile advertiser 
PATCH  http://localhost:3000/advertiser/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODEyYzA0Mjc4MTZkM2UwNzg1YWI2ZSIsImVtYWlsIjoic29icmFsY2Fzc2lxdWVAZ21haWwuY29tIiwiaWF0IjoxNzUzMzA4ODQ2LCJleHAiOjE3NTMzOTUyNDZ9.3Wvjb0Al0SgCxUty0_rWQXb631fu4nYKi5lf2M5-_S0
Content-Type: application/json

{
    "name":"cassiano2",
   "advertiserData": {
        "isAdvertiser": true,
        "companyName": "airbnb luxos"
    }
}
### create announcement  
POST http://localhost:3000/advertiser/announcement
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODEyYzA0Mjc4MTZkM2UwNzg1YWI2ZSIsImVtYWlsIjoic29icmFsY2Fzc2lxdWVAZ21haWwuY29tIiwiaWF0IjoxNzUzMzA4ODQ2LCJleHAiOjE3NTMzOTUyNDZ9.3Wvjb0Al0SgCxUty0_rWQXb631fu4nYKi5lf2M5-_S0

{
    
}