### auth signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "emprego1231231@gmail.com",
    "password": "TesteReal",
    "name": "Cassiano5"
}
### verify email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
    "email": "emprego1231231@gmail.com",
    "verificationToken":"54034"
}

### resend verification token / signup or password
POST http://localhost:3000/auth/resend-verification-token
Content-Type: application/json

{
    "email":"emprego1231231@gmail.com",
    "type":"verification"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"emprego1231231@gmail.com",
    "password":"TesteReal"
}
### logout 
POST http://localhost:3000/auth/logout

### get user 
POST http://localhost:3000/auth/user
Content-Type: application/json

{
    "email":"emprego1231231@gmail.com"
}