### auth signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "emprego1231231@gmail.com",
    "password": "TesteReal",
    "name": "Cassiano5"
}
### verify email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
    "email": "emprego1231231@gmail.com",
    "verificationToken":"51132"
}
